# Generated by Django 3.2.6 on 2021-08-24 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_users_options'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.users')),
            ],
            options={
                'db_table': 'carts',
            },
        ),
        migrations.AlterModelOptions(
            name='manufactures',
            options={'verbose_name': '製作者', 'verbose_name_plural': '製作者'},
        ),
        migrations.AlterModelOptions(
            name='productpictures',
            options={'ordering': ['order'], 'verbose_name': '製品画像', 'verbose_name_plural': '製品画像'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': '製品', 'verbose_name_plural': '製品'},
        ),
        migrations.AlterModelOptions(
            name='producttypes',
            options={'verbose_name': '製品タイプ', 'verbose_name_plural': '製品タイプ'},
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.carts')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.products')),
            ],
            options={
                'db_table': 'cart_items',
                'unique_together': {('product', 'cart')},
            },
        ),
    ]
